### ISSUE TITLE
code does not work:(

### ISSUE THREAD

**Issue by vvidov** [PacktPublishing/Electron-Projects#1]
code does not work:(

**Comment by DenysVuika** [comment]
Can you please be more precise?

**Comment by vvidov** [comment]
Just Download code Form chapter4 and prove it, you see App and when you
click in snap There is an Error.

**Comment by DenysVuika** [comment]
what is the OS? what kind of error? please open a proper issue request with details that can actually help addressing the problem

**Comment by vvidov** [comment]
I do not have all in my head, I will see later and give you a feedback:)

**Comment by vvidov** [comment]
sorry, it is my mistake:(
