### ISSUE TITLE
showSaveDialog

### ISSUE THREAD

**Issue by DigiTorus86** [PacktPublishing/Electron-Projects#3]
In the Chapter 2 menu.js code:

dialog.showSaveDialog(window, options, filename => {
console.log(`Filename: ${filename}`);  // added - never gets called?
    if (filename) {
      console.log(`Saving content to the file: ${filename}`);
      fs.writeFileSync(filename, arg);
    }
  });

...doesn't save the file (or execute any of the following statements) after the dialog is shown and a filename is entered.  When I changed it to a synchronous dialog call, then it started to actually save the file:

let filename = dialog.showSaveDialogSync(window, options); 
console.log(`Filename: ${filename}`);
if (filename) {
        console.log(`Saving content to the file: ${filename}`);
        fs.writeFileSync(filename, arg);
}

**Comment by DenysVuika** [comment]
Updated the example, thanks.
