### ISSUE TITLE
Chapter 1 2 needs to be updated on your packet book

### ISSUE THREAD

**Issue by ramAdam** [PacktPublishing/Electron-Projects#88]
None of the example code in your book reflects the code on Github, 

i think it's a good book, you need to update it.

**Comment by DenysVuika** [comment]
Can you please explain more on what do you find not reflecting the code?

**Comment by shruthis-shetty** [comment]
Hi @ramAdam ,
The code files have been updated because of the version update. Please check the version and execute the codes.

**Comment by ramAdam** [comment]
@shruthis-shetty and @DenysVuika, Thank you for the update, i'll have a look.
